
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


min_height = 600
min_width = 800
max_height = 1440
max_width = 1024
window = Tk()
 
#Get the current screen width and height
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()

window.geometry(f"{screen_width}x{screen_height}")
window.configure(bg = "#FFFFFF")
# creating main tkinter window/toplevel
 
# this will create a label widget
l1 = Label(window, text = "Height")
l2 = Label(window, text = "Width")
 
# grid method to arrange labels in respective
# rows and columns as specified
l1.grid(row = 0, column = 0, pady = 2) 
l2.grid(row = 3, column = 2, pady = 2,columnspan=100)

image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
# image_image_1 = image_image_1.subsample(2, 2)
Label(window, image=image_image_1,bg='#FFFFFF').grid(row = 0, column = 2,
     rowspan = 2, padx = 5, pady = 5)

window.resizable(True, True)
window.mainloop()
